[package]
name = "clicolors-control"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[features]
default = ["terminal_autoconfig"]
terminal_autoconfig = []

[dependencies]
lazy_static = "0"

[target.'cfg(windows)'.dependencies]
winapi = "0"
kernel32-sys = "0"

[target.'cfg(unix)'.dependencies]
libc = "0"
